spring:
  application:
    name: eSnack24API
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://10.10.10.123:13307/snackdb
    username: snackdbuser
    password: snackdbuser

    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      connection-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: org.esnack24api.esnack24api.**.dto

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
      location: upload
      enabled: true

org:
  hyeong:
    accessTime: 1
    refreshTime: 10080
    alwaysNew: true
    upload:
      path: upload

logging:
  level:
    org.springframework.security.web: TRACE

PAYPAL:
  CLIENT:
    ID: ARXsGAth3VQXmiZa7fzIK0DwKdZyAzwGCRD_fpxBdWRpvo2QezzYbWqHpckTcGn8XpjHUPNVuIu7GLTh
    SECRET: EKsv5jHmf8NRSF3rDRS41PCc8m_c3UJcXDT4pZ3o1FPK1Tlujy7kdd1tuaiWiiHvesVmmIVAPaRMyt0o